use `egetpot` to parse parameters
- parse parameter of tbg with egetopt
- move evaluation of environment default parameter to while loop

diff --git a/src/tools/bin/tbg b/src/tools/bin/tbg
--- a/src/tools/bin/tbg
+++ b/src/tools/bin/tbg
@@ -160,12 +160,12 @@ help()
     echo "TBG (template batch generator)"
     echo "create a new folder for a batch job and copy in all important files"
     echo ""
-    echo "usage: tbg -c cfgFile [-s submitsystem] [-t templateFile] [-p project] [-o \"VARNAME1=10 VARNAME2=5\"] [-h] destinationPath"
+    echo "usage: tbg -c cfgFile [-s [submitsystem]] [-t [templateFile]] [-p project] [-o \"VARNAME1=10 VARNAME2=5\"] [-h] destinationPath"
     echo ""
     echo "-c | --cfg      file           - Configuration file to set up batch file."
-    echo "-s | --submit   command        - Submit command (qsub, \"qsub -h\", sbatch, ...)"
+    echo "-s | --submit   [command]      - Submit command (qsub, \"qsub -h\", sbatch, ...)"
     echo "                                 Default: via export TBG_SUBMIT"
-    echo "-t | --tpl      file           - Template to create a batch file from."
+    echo "-t | --tpl      [file]         - Template to create a batch file from."
     echo "                                 tbg will use stdin, if no file is specified."
     echo "                                 Default: via export TBG_TPLFILE"
     echo "-p | --project  folder         - Project folder containing sourcecode and binaries"
@@ -190,8 +190,23 @@ help()
 initCall="$0 $*"
 projectPath="."
 
-# options may be followed by one colon to indicate they have a required argument
-OPTS=`getopt -o p:t:c:s:o:h -l project:,tpl:,cfg:,submit:,help -- "$@"`
+pathToegetopt=`which egetopt`
+if [ $? -eq 0 ] ; then
+    pathToegetopt=`dirname $pathToegetopt`
+else
+    pathToegetopt=`dirname $0`
+fi
+
+egetoptTool=`which $pathToegetopt/egetopt`
+if [ $? -ne 0 ] ; then
+    echo "Can't find program egetopt" >&2
+    exit
+fi
+
+# options may be followed by 
+# - one colon to indicate they have a required argument
+# - two colon to indicate they have a optional argument
+OPTS=`$egetoptTool -o p:t::c:s::o:h -l project:,tpl::,cfg:,submit::,help -n tbg ++ "$@"`
 if [ $? != 0 ] ; then
     # something went wrong, getopt will put out an error message for us
     exit 1
@@ -199,17 +214,11 @@ fi
 
 eval set -- "$OPTS"
 
-# default parameters from environment variables (e.g. in a .profile file)
-#   -s | --submit
-submit_command=${TBG_SUBMIT:-""}
-#   -t | --tpl
-tooltpl_file=${TBG_TPLFILE:-""}
-
 # parser
 while true ; do
     case "$1" in
         -s|--submit)
-            submit_command="$2"
+            submit_command=${2:-$TBG_SUBMIT}
             shift
             ;;
        -p|--project)
@@ -225,7 +234,7 @@ while true ; do
             shift
             ;;
        -t|--tpl)
-            tooltpl_file="$2"
+            tooltpl_file=${2:-$TBG_TPLFILE}
             shift
             ;;
         -h|--help)
