add submit command check, change documentation
- change github annotations
- add check whether a submit system is set with -s|--submit

diff --git a/src/tools/bin/tbg b/src/tools/bin/tbg
--- a/src/tools/bin/tbg
+++ b/src/tools/bin/tbg
@@ -164,10 +164,10 @@ help()
     echo ""
     echo "-c | --cfg      file           - Configuration file to set up batch file."
     echo "-s | --submit   [command]      - Submit command (qsub, \"qsub -h\", sbatch, ...)"
-    echo "                                 Default: via export TBG_SUBMIT"
+    echo "                                 Default: [submitsystem] via export TBG_SUBMIT"
     echo "-t | --tpl      [file]         - Template to create a batch file from."
     echo "                                 tbg will use stdin, if no file is specified."
-    echo "                                 Default: via export TBG_TPLFILE"
+    echo "                                 Default: [templateFile] via export TBG_TPLFILE"
     echo "-p | --project  folder         - Project folder containing sourcecode and binaries"
     echo "                                 Default: current directory"
     echo "-o                             - Overwrite any template variable:"
@@ -200,15 +200,15 @@ fi
 egetoptTool=`which $pathToegetopt/egetopt`
 if [ $? -ne 0 ] ; then
     echo "Can't find program egetopt" >&2
-    exit
+    exit 1
 fi
 
 # options may be followed by 
-# - one colon to indicate they have a required argument
-# - two colon to indicate they have a optional argument
+# - one colon to indicate they has a required argument
+# - two colons to indicate they has a optional argument
 OPTS=`$egetoptTool -o p:t::c:s::o:h -l project:,tpl::,cfg:,submit::,help -n tbg ++ "$@"`
 if [ $? != 0 ] ; then
-    # something went wrong, getopt will put out an error message for us
+    # something went wrong, egetopt will put out an error message for us
     exit 1
 fi
 
@@ -219,6 +219,10 @@ while true ; do
     case "$1" in
         -s|--submit)
             submit_command=${2:-$TBG_SUBMIT}
+            if [ -z "$submit_command" ] ; then
+                echo "missing submit command for -s|--submit" >&2
+                exit 1
+            fi
             shift
             ;;
        -p|--project)
